---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mikrolb:controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mikrolb:controller
subjects:
- kind: ServiceAccount
  name: mikrolb-controller
  namespace: mikrolb-system
