---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - issuer.yaml
  - certificate.yaml

replacements:
  - source:
      kind: Certificate
      name: mikrolb-webhook
      fieldPath: metadata.namespace
    targets:
      - select:
          kind: Certificate
          name: mikrolb-webhook
        fieldPaths:
          - spec.dnsNames.0
          - spec.dnsNames.1
        options:
          delimiter: "."
          index: 1  # replaces the 2nd segment (0-indexed)
